public class ConedReeds extends Stop {
    private String reedType;
    private double scalingFactor;

    public ConedReeds(String name, int pitch, int numberOfPipes, String reedType, double scalingFactor) {
        super(name, new Rank[]{new Rank(pitch, numberOfPipes)});
        this.reedType = reedType;
        this.scalingFactor = scalingFactor;
    }

    public String getReedType() {
        return reedType;
    }

    public void setReedType(String reedType) {
        this.reedType = reedType;
    }

    public double getScalingFactor() {
        return scalingFactor;
    }

    public void setScalingFactor(double scalingFactor) {
        this.scalingFactor = scalingFactor;
    }

    // Method to calculate scaled diameter based on scaling factor
    public double calculateScaledDiameter(double originalDiameter) {
        return originalDiameter * scalingFactor;
    }

    // Method to generate sound for coned reeds
    public void generateSound() {
        for (Rank rank : getRanks()) {
            int pitch = rank.getPitch();
            int numberOfPipes = rank.getNumberOfPipes();
            double originalDiameter = 12.5; // Assuming an original diameter of 12.5 for coned reeds
            
            // Calculate scaled diameter based on scaling factor
            double scaledDiameter = calculateScaledDiameter(originalDiameter);
            
            // Implement sound generation logic for coned reeds at full length
            System.out.println("Sound for ConedReeds stop with pitch " + pitch + " and scaled diameter " + scaledDiameter + " generated by " + reedType + " reed at full length.");
        }
    }
}
