public class Krummhorns extends Stop {
    private String reedType;
    private double scalingFactor;

    public Krummhorns(String name, int pitch, int numberOfPipes, String reedType, double scalingFactor) {
        super(name, new Rank[]{new Rank(pitch, numberOfPipes)});
        this.reedType = reedType;
        this.scalingFactor = scalingFactor;
    }

    public String getReedType() {
        return reedType;
    }

    public void setReedType(String reedType) {
        this.reedType = reedType;
    }

    public double getScalingFactor() {
        return scalingFactor;
    }

    public void setScalingFactor(double scalingFactor) {
        this.scalingFactor = scalingFactor;
    }

    // Method to calculate scaled diameter based on scaling factor
    public double calculateScaledDiameter(double originalDiameter) {
        return originalDiameter * scalingFactor;
    }

    // Method to generate sound for krummhorns
    public void generateSound() {
        for (Rank rank : getRanks()) {
            int pitch = rank.getPitch();
            int numberOfPipes = rank.getNumberOfPipes();
            double originalDiameter = 15.0; // Assuming an original diameter of 15.0 for krummhorns
            double originalLength = 1.0; // Assuming original length of 1.0
            
            // Calculate scaled diameter and half-length based on scaling factor
            double scaledDiameter = calculateScaledDiameter(originalDiameter);
            double scaledLength = originalLength / 2; // Half the length for krummhorns
            
            // Implement sound generation logic for krummhorns
            System.out.println("Sound for Krummhorns stop with pitch " + pitch + " and scaled diameter " + scaledDiameter + " at half-length generated by " + reedType + " reed.");
        }
    }
}
